version: '3'

services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - proxy
      - redis
  client-server:
    build:
      context: ./client-server
      dockerfile: Dockerfile
  front-end:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
      - proxy
    tty: true
