/**
 * @fileoverview gRPC-Web generated client stub for devices
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: device.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.devices = require('./device_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.devices.DeviceServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.devices.DeviceServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.devices.DeviceUpdateRequest,
 *   !proto.devices.DeviceUpdateResponse>}
 */
const methodDescriptor_DeviceService_DeviceUpdate = new grpc.web.MethodDescriptor(
  '/devices.DeviceService/DeviceUpdate',
  grpc.web.MethodType.UNARY,
  proto.devices.DeviceUpdateRequest,
  proto.devices.DeviceUpdateResponse,
  /**
   * @param {!proto.devices.DeviceUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.devices.DeviceUpdateResponse.deserializeBinary
);


/**
 * @param {!proto.devices.DeviceUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.devices.DeviceUpdateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.devices.DeviceUpdateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.devices.DeviceServiceClient.prototype.deviceUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/devices.DeviceService/DeviceUpdate',
      request,
      metadata || {},
      methodDescriptor_DeviceService_DeviceUpdate,
      callback);
};


/**
 * @param {!proto.devices.DeviceUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.devices.DeviceUpdateResponse>}
 *     Promise that resolves to the response
 */
proto.devices.DeviceServicePromiseClient.prototype.deviceUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/devices.DeviceService/DeviceUpdate',
      request,
      metadata || {},
      methodDescriptor_DeviceService_DeviceUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.devices.DeviceListRequest,
 *   !proto.devices.DeviceListResponse>}
 */
const methodDescriptor_DeviceService_DeviceList = new grpc.web.MethodDescriptor(
  '/devices.DeviceService/DeviceList',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.devices.DeviceListRequest,
  proto.devices.DeviceListResponse,
  /**
   * @param {!proto.devices.DeviceListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.devices.DeviceListResponse.deserializeBinary
);


/**
 * @param {!proto.devices.DeviceListRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.devices.DeviceListResponse>}
 *     The XHR Node Readable Stream
 */
proto.devices.DeviceServiceClient.prototype.deviceList =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/devices.DeviceService/DeviceList',
      request,
      metadata || {},
      methodDescriptor_DeviceService_DeviceList);
};


/**
 * @param {!proto.devices.DeviceListRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.devices.DeviceListResponse>}
 *     The XHR Node Readable Stream
 */
proto.devices.DeviceServicePromiseClient.prototype.deviceList =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/devices.DeviceService/DeviceList',
      request,
      metadata || {},
      methodDescriptor_DeviceService_DeviceList);
};


module.exports = proto.devices;

